-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.barco
(
    matricula character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    cuota money,
    n_amarre integer,
    n_socio integer,
    CONSTRAINT barco_pkey PRIMARY KEY (matricula)
);

CREATE TABLE IF NOT EXISTS public.patron
(
    dni_patron character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default",
    telefono integer,
    matricula character varying(50) COLLATE pg_catalog."default",
    id_salida character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dni_patron PRIMARY KEY (dni_patron)
);

CREATE TABLE IF NOT EXISTS public.salida
(
    id_salida character varying(50) COLLATE pg_catalog."default" NOT NULL,
    destino character varying(50) COLLATE pg_catalog."default",
    f_salida date,
    h_salida time without time zone,
    matricula character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT id_salida PRIMARY KEY (id_salida)
);

CREATE TABLE IF NOT EXISTS public.socio
(
    n_socio integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT socio_pkey PRIMARY KEY (n_socio)
);

ALTER TABLE IF EXISTS public.barco
    ADD CONSTRAINT barco_n_socio_fkey FOREIGN KEY (n_socio)
    REFERENCES public.socio (n_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patron
    ADD CONSTRAINT patron_id_salida_fkey FOREIGN KEY (id_salida)
    REFERENCES public.salida (id_salida) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.patron
    ADD CONSTRAINT patron_matricula_fkey FOREIGN KEY (matricula)
    REFERENCES public.barco (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.salida
    ADD CONSTRAINT salida_matricula_fkey FOREIGN KEY (matricula)
    REFERENCES public.barco (matricula) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;